import { GridColumn, GridRow } from "./types";

export const MOCK_COLUMNS: GridColumn[] = [
    { id: "patientName", name: "Patient Name", type: "TEXT", width: 200 },
    { id: "dos", name: "DOS", type: "DATE", width: 120 },
    { id: "returned", name: "Returned", type: "CHECKBOX", width: 100 },
    { id: "complete", name: "Complete", type: "CHECKBOX", width: 100 },
    { id: "packingSlip", name: "Packing Slip", type: "CHECKBOX", width: 100 },
    { id: "hasVoiceRecord", name: "Has Voice Record", type: "CHECKBOX", width: 130 },
    { id: "rx", name: "RX", type: "CHECKBOX", width: 80 },
    { id: "clinicalNotes", name: "Clinical Notes", type: "CHECKBOX", width: 120 },
    { id: "sameSimilar", name: "Same/Similar", type: "CHECKBOX", width: 120 },
    { id: "pod", name: "POD", type: "CHECKBOX", width: 80 },
    { id: "attachments", name: "Attachments", type: "FILE", width: 150 },
    { id: "tracking", name: "Tracking", type: "TEXT", width: 150 },
    { id: "trackingStatus", name: "Tracking Status", type: "SELECT", width: 150, options: ["Delivered", "In Transit", "Pending", "Exception", "Label Created"] },
    { id: "deliveredDate", name: "Delivered Date", type: "DATE", width: 130 },
    { id: "notes", name: "Notes", type: "LONG_TEXT", width: 250 },
    { id: "address", name: "Address", type: "TEXT", width: 200 },
    { id: "city", name: "City", type: "TEXT", width: 150 },
    { id: "state", name: "State", type: "TEXT", width: 100 },
    { id: "zip", name: "Zip", type: "TEXT", width: 100 },
    { id: "dob", name: "DOB", type: "DATE", width: 120 },
    { id: "patientId", name: "Patient ID", type: "TEXT", width: 120 },
    { id: "product", name: "Product", type: "SELECT", width: 150, options: ["L0457", "L1833", "L1906", "L3170"] },
    { id: "billed", name: "Billed", type: "CHECKBOX", width: 100 },
    { id: "paid", name: "Paid", type: "CURRENCY", width: 130 },
    { id: "amount", name: "Amount", type: "CURRENCY", width: 130 },
    { id: "secondaryPay", name: "Secondary Pay", type: "CURRENCY", width: 140 },
    { id: "deductible", name: "Deductible", type: "CURRENCY", width: 130 },
    { id: "billingNotes", name: "Billing Notes", type: "LONG_TEXT", width: 250 },
    { id: "reversalNeeded", name: "Reversal Needed", type: "CHECKBOX", width: 140 },
    { id: "method", name: "Method", type: "TEXT", width: 120 },
    { id: "completed", name: "Completed", type: "CHECKBOX", width: 100 },
    { id: "reversalForm", name: "Reversal Form", type: "FILE", width: 150 },
    { id: "lastModified", name: "Last Modified", type: "DATE", width: 160 },
    { id: "lastModifiedBy", name: "Last Modified By", type: "USER", width: 160 },
    { id: "reasonForReturn", name: "Reason for Return", type: "SELECT", width: 180, options: ["BAD STATE", "SNS FAILED", "No Answer"] },
    { id: "summaryState", name: "Summary (State)", type: "TEXT", width: 300 },
];

export const MOCK_ROWS: GridRow[] = Array.from({ length: 100 }).map((_, i) => ({
    id: `row-${i}`,
    patientName: `Patient ${i + 1}`,
    dos: new Date(2025, i % 12, (i % 28) + 1).toISOString().split('T')[0],
    returned: i % 10 === 0,
    complete: i % 5 === 0,
    packingSlip: i % 3 === 0,
    hasVoiceRecord: i % 2 === 0,
    rx: i % 4 === 0,
    clinicalNotes: i % 2 === 0,
    sameSimilar: i % 7 === 0,
    pod: i % 3 === 0,
    attachments: i % 5 === 0 ? [{ name: "doc.pdf" }] : [],
    tracking: `1ZK58464A8000${i.toString().padStart(4, '0')}`,
    trackingStatus: "",
    deliveredDate: "",
    notes: i % 10 === 0 ? "Returned" : "Standard delivery",
    address: `${100 + i} Script Ln`,
    city: ["New York", "Buffalo", "Lake Charles", "Hailey"][i % 4],
    state: ["NY", "LA", "ID", "CA"][i % 4],
    zip: `9021${i % 9}`,
    dob: new Date(1950 + (i % 40), i % 12, (i % 28) + 1).toISOString().split('T')[0],
    patientId: `PID-${1000 + i}`,
    product: ["L0457", "L1833", "L1906", "L3170"][i % 4],
    billed: i % 2 === 0,
    paid: (Math.random() * 500).toFixed(2),
    amount: (Math.random() * 1000).toFixed(2),
    secondaryPay: (Math.random() * 100).toFixed(2),
    deductible: (Math.random() * 200).toFixed(2),
    billingNotes: "",
    reversalNeeded: i % 20 === 0,
    method: "Direct",
    completed: i % 5 === 0,
    reversalForm: [],
    lastModified: new Date().toISOString(),
    lastModifiedBy: "Admin",
    reasonForReturn: i % 15 === 0 ? "BAD STATE" : "",
    summaryState: i % 15 === 0 ? "Initial" : "Processing"
}));
